# -*- coding: utf-8 -*-
"""pandas Operations

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0lfafEd-Ox2nZuBcBDDOdDIgeHe8Nms
"""

import pandas as pd
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
series = pd.Series(arr)
print(series)

scalar = 5
series = pd.Series(scalar, index=['a', 'b', 'c'])
print(series)

data = {'a': 10, 'b': 20, 'c': 30}
series = pd.Series(data)
print(series)

series = pd.Series([10, 20, 30])
df = pd.DataFrame(series, columns=['Column Name'])
print(df)

data = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}, {'name': 'Charlie', 'age': 35}]
df = pd.DataFrame(data)
print(df)

data = np.array([[10, 20], [30, 40], [50, 60]])
df = pd.DataFrame(data, columns=['Column 1', 'Column 2'])
print(df)

data = np.array([('Alice', 25), ('Bob', 30), ('Charlie', 35)], dtype=[('name', 'U10'), ('age', int)])
df = pd.DataFrame(data)
print(df)

import pandas as pd

# Create the weather DataFrame
data = {
    'City': ['Delhi', 'Bengaluru', 'Chennai', 'Mumbai', 'Kolkata'],
    'MaxTemp': [40, 31, 35, 29, 39],
    'MinTemp': [32, 25, 27, 21, 23],
    'RainFall': [24.1, 36.2, 40.8, 35.2, 41.8]
}

weather = pd.DataFrame(data)
print(weather)

# Find the maximum temperature
max_temp = weather['MaxTemp'].max()
print("\nMaximum temperature:", max_temp)  # Maximum temperature in the weather DataFrame

# Find the minimum temperature
min_temp = weather['MinTemp'].min()
print("\nMinimum temperature:", min_temp)  # Minimum temperature in the weather DataFrame

# (b) Compute mean of column RainFall
rainfall_mean = weather['RainFall'].mean()
print("\nMean of RainFall column:", rainfall_mean)

# (c) Compute median of the MaxTemp column
maxtemp_median = weather['MaxTemp'].median()
print("\nMedian of MaxTemp column:", maxtemp_median)

import pandas as pd

# Create the DataFrame
data = {
    'school_code': ['S1', 'S2', 'S3', 'S4', 'S5', 'S6'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco', 'Gino Mcneill', 'Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_birth': ['15/05/2002', '17/05/2002', '16/02/1999', '25/09/1998', '11/05/2002', '15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159]
}

df = pd.DataFrame(data)
print(df)

# Find the minimum and maximum values of height and age columns
min_height = df['height'].min()
max_height = df['height'].max()
min_age = df['age'].min()
max_age = df['age'].max()

print("\nMinimum height:", min_height)
print("Maximum height:", max_height)
print("Minimum age:", min_age)
print("Maximum age:", max_age)